@startuml activity_lab3_1
title "Диаграмма активности"

|Менеджер по работе с клиентами|
start 
:Оформление заказа клиента;
:Передать заказ;

|Инженер по сборке|
:Запросить необходимые компоненты;

|Завскладом|
:Проверить наличие комплектующих;
:Собрать комплектующие;
:Передать комплектующие;

|Инженер по сборке|
:Собрать компьютер;
:Передать компьютер;


|Инженер по тестированию|
repeat :Произвести тестирование\n компьютера;
    if(Тестирование пройдено?) then (да)
        :Передать компьютер на склад;
        |Завскладом|
        :Оформить накладнаю на компьютер;
        :Хранение компьютера;
        :Выдать компьютер;

        |Менеджер по работе с клиентами|
        :Оформить документацию;
        :Выдать заказ;
        stop
    else (нет)
    endif
|Инженер по сборке|
:Устранить неполадки в сборке;
backward :Повторная отправка на тестирование; 

@enduml

