@startuml activity_lab3_2
title "Диаграмма деятельности потока событий прецедента "Работа с заказом""

start 
repeat 
    if (Вы забыли логин или пароль?) then (да)
        :Выйти из системы;
        stop
    else (нет)
        :Ввести логин и пароль;
    endif
repeat while (Данные введены корректно?) is (нет) not (да)

repeat :Выбор действия;
    switch ()
        case () 
            partition "Процесс добавления заказа" {
                :Добавить заказ;
                switch (Выбрать тип компьютера) 
                    case ()
                        :Выбрать Настольный ПК;
                    case ()
                        :Выбрать Ноутбук;
                endswitch
                :Выбрать клиента из базы;
                repeat 
                    :Выбрать комплектующие;
                    switch ()
                        case ()
                            :Все комплектующие\n выбраны;
                            :Запись введенных\n данных;
                        case ()
                            :Нет всех комплектующих;
                            :Перейти к выбору\n новых комплектующих;
                        case ()
                            :Комплектующих нет;
                    endswitch
                repeat while (Перейти к выбору) is (да) not (нет)
                :Выйти из меню выбора комплектующих;
            }
        case ()
            :Изменить заказ;
        case ()
            :Просмотреть заказ;
        case ()
            :Удалить заказ;
    endswitch
repeat while (Обработать заказ?) is (да) not (нет) 
:Выйти из системы;
stop
@enduml
