@startuml state_lab_5
title "Диаграмма состояний"


[*] --> Инициализация : Заказ создан
Инициализация: вход / Сохранить дату заказа
Инициализация: выполнение / Внести информацию о заказе

Инициализация --> Открыт : Инициализация завершена
Открыт: выход / * Создание пункта заказа

Открыт --> Отменен : Заказ отменен
Отменен: выход / Сохранить дату отмены

Открыт --> Закрыт : Заполнены все позиции заказа
Закрыт: выполнение / Выписать счет

Отменен --> [*] : Удаление\n пункта заказа
Закрыт --> [*] : Счет\n выписан
@enduml